name: Chrome
on: [push, pull_request]

jobs:
  build:
    name: Setup Chrome
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install selenium
        run: |
          python --version 
          pip install selenium
      - name: Install and run script chrome
        run: |
          python test_selenium_chrome.py
      - name: Install and run script chrome
        run: mvn install
        working-directory: java
      - name: Install and run script firefox
        run: |
          python test_selenium_firefox.py
