name: Chrome
on: [push, pull_request]

jobs:
  build:
    name: Setup Chrome
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install selenium
        run: |
          python --version 
          pip install selenium
      - name: Install and run script chrome node
        run: |
          npm install
          npm run test
        working-directory: nodeTests
      - name: Install and run script chrome python
        run: |
          python test_selenium_chrome.py
      - name: Install and run script chrome java
        run: |
          mvn install
          mvn test
        working-directory: java
      - name: Install and run script firefox java
        run: |
          python test_selenium_firefox.py
