name: Chrome
on: [push, pull_request]

jobs:
  build:
    name: Setup Chrome
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install selenium
        run: |
          python --version 
          pip3 install selenium
      - name: Install and run script chrome
        run: |
          python3 test_selenium_chrome.py
      - name: Install and run script firefox
        run: |
          python3 test_selenium_firefox.py